version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: ecommerce
  web:
    build: ./django_ecommerce/ecommerce
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_ecommerce/ecommerce:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: ./my-app
    volumes:
      - ./my-app:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "start"]